-- MySQL Script generated by MySQL Workbench
-- Mon Nov 22 18:29:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SalaryManagementDB
-- -----------------------------------------------------

USE jVJJMgOQhb;

-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `address_id` INT(4) NOT NULL AUTO_INCREMENT,
  `zipcode` CHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `state` CHAR(2) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business` ;

CREATE TABLE IF NOT EXISTS `Business` (
  `business_id` TINYINT(2) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `address` INT(4) NULL,
  PRIMARY KEY (`business_id`),
  INDEX `BUSINESS_ADDRESS_FK_idx` (`address` ASC) VISIBLE,
  CONSTRAINT `BUSINESS_ADDRESS_FK`
    FOREIGN KEY (`address`)
    REFERENCES `Address` (`address_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Owner` ;

CREATE TABLE IF NOT EXISTS `Owner` (
  `owner_id` TINYINT(2) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` CHAR(11) NOT NULL,
  `business` TINYINT(2) NULL,
  PRIMARY KEY (`owner_id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `OWNER_BUSINESS_FK_idx` (`business` ASC) VISIBLE,
  CONSTRAINT `OWNER_BUSINESS_FK`
    FOREIGN KEY (`business`)
    REFERENCES `Business` (`business_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employee_id` INT(4) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `number` CHAR(11) NOT NULL,
  `business` TINYINT(2) NOT NULL,
  PRIMARY KEY (`employee_id`, `business`),
  INDEX `EMPLOYEE_BUSINESS_FK_idx` (`business` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_BUSINESS_FK`
    FOREIGN KEY (`business`)
    REFERENCES `Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `manager_id` INT(2) NOT NULL AUTO_INCREMENT,
  `manager_type` VARCHAR(45) NOT NULL,
  `employee` INT(4) NOT NULL,
  PRIMARY KEY (`manager_id`, `employee`),
  INDEX `MANAGER_EMPLOYEEID_FK_idx` (`employee` ASC) VISIBLE,
  CONSTRAINT `MANAGER_EMPLOYEEID_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Position` ;

CREATE TABLE IF NOT EXISTS `Position` (
  `position_id` INT(4) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `401k Plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `401k Plan` ;

CREATE TABLE IF NOT EXISTS `401k Plan` (
  `plan_id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `percentage` DECIMAL(3,2) NOT NULL,
  `employer_contribution` DECIMAL(3,2) NULL,
  `type` VARCHAR(20) NULL,
  PRIMARY KEY (`plan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `State` ;

CREATE TABLE IF NOT EXISTS `State` (
  `state_id` CHAR(2) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`state_id`),
  UNIQUE INDEX `state_id_UNIQUE` (`state_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Income Tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Income Tax` ;

CREATE TABLE IF NOT EXISTS `Income Tax` (
  `tax_type` VARCHAR(20) NOT NULL,
  `year` YEAR(4) NOT NULL,
  PRIMARY KEY (`tax_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `State Income Tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `State Income Tax` ;

CREATE TABLE IF NOT EXISTS `State Income Tax` (
  `state_tax_id` INT(4) NOT NULL AUTO_INCREMENT,
  `state` CHAR(2) NOT NULL,
  `income_tax` VARCHAR(20) NOT NULL,
  INDEX `STATEINCOMETAX_TAX_FK_idx` (`income_tax` ASC) VISIBLE,
  PRIMARY KEY (`state_tax_id`),
  INDEX `STATEINCOMETAX_STATE_FK_idx` (`state` ASC) VISIBLE,
  CONSTRAINT `STATEINCOMETAX_STATE_FK`
    FOREIGN KEY (`state`)
    REFERENCES `State` (`state_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `STATEINCOMETAX_TAX_FK`
    FOREIGN KEY (`income_tax`)
    REFERENCES `Income Tax` (`tax_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salary` ;

CREATE TABLE IF NOT EXISTS `Salary` (
  `salary_id` INT(6) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NOT NULL,
  `year` CHAR(4) NOT NULL,
  `state_tax` INT(4) NULL,
  `401k_plan` TINYINT(1) NULL,
  PRIMARY KEY (`salary_id`),
  INDEX `SALARY_PLAN_FK_idx` (`401k_plan` ASC) VISIBLE,
  INDEX `SALARY_STATE_FK_idx` (`state_tax` ASC) VISIBLE,
  CONSTRAINT `SALARY_PLAN_FK`
    FOREIGN KEY (`401k_plan`)
    REFERENCES `401k Plan` (`plan_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `SALARY_STATE_FK`
    FOREIGN KEY (`state_tax`)
    REFERENCES `State Income Tax` (`state_tax_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank Account` ;

CREATE TABLE IF NOT EXISTS `Bank Account` (
  `bank_id` INT(4) NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(45) NOT NULL,
  `bank_number` VARCHAR(13) NOT NULL,
  `routing_number` CHAR(9) NOT NULL,
  PRIMARY KEY (`bank_id`),
  UNIQUE INDEX `bank_number_UNIQUE` (`bank_number` ASC) VISIBLE,
  UNIQUE INDEX `routing_number_UNIQUE` (`routing_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Account` ;

CREATE TABLE IF NOT EXISTS `Employee Account` (
  `account_id` INT(4) NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL,
  `employee` INT(4) NULL,
  PRIMARY KEY (`account_id`),
  INDEX `EMPLOYEEACCOUNT_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  UNIQUE INDEX `employee_UNIQUE` (`employee` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEEACCOUNT_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment` ;

CREATE TABLE IF NOT EXISTS `Payment` (
  `payment_id` INT(8) NOT NULL AUTO_INCREMENT,
  `created` TIMESTAMP NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schedule` ;

CREATE TABLE IF NOT EXISTS `Schedule` (
  `schedule_id` INT(4) NOT NULL AUTO_INCREMENT,
  `days` VARCHAR(7) NOT NULL,
  `time` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`schedule_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Supplemental Wage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supplemental Wage` ;

CREATE TABLE IF NOT EXISTS `Supplemental Wage` (
  `supplemental_wage_id` INT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  `state_tax` INT(4) NULL,
  PRIMARY KEY (`supplemental_wage_id`),
  INDEX `SUPPLEMENTALWAGE_TAX_idx` (`state_tax` ASC) VISIBLE,
  CONSTRAINT `SUPPLEMENTALWAGE_TAX`
    FOREIGN KEY (`state_tax`)
    REFERENCES `State Income Tax` (`state_tax_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reimbursement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reimbursement` ;

CREATE TABLE IF NOT EXISTS `Reimbursement` (
  `reimbursement_id` INT(8) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`reimbursement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tax Bracket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tax Bracket` ;

CREATE TABLE IF NOT EXISTS `Tax Bracket` (
  `bracket_id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `rate` DECIMAL(4,2) NOT NULL,
  `range_start` DECIMAL(8,2) NOT NULL,
  `range_end` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`bracket_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wage` ;

CREATE TABLE IF NOT EXISTS `Wage` (
  `wage_id` INT(6) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(5,2) NOT NULL,
  `created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`wage_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Business Reimbursement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business Reimbursement` ;

CREATE TABLE IF NOT EXISTS `Business Reimbursement` (
  `business_reimbursement_id` INT(8) NOT NULL AUTO_INCREMENT,
  `business` TINYINT(1) NOT NULL,
  `reimbursement` INT(8) NOT NULL,
  INDEX `BUSINESSREIMBURSEMENTS_BUSINESS_FK_idx` (`business` ASC) VISIBLE,
  INDEX `BUSINESSREIMBURSEMENT_REIMBURSEMENT_FK_idx` (`reimbursement` ASC) VISIBLE,
  PRIMARY KEY (`business_reimbursement_id`),
  CONSTRAINT `BUSINESSREIMBURSEMENTS_BUSINESS_FK`
    FOREIGN KEY (`business`)
    REFERENCES `Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BUSINESSREIMBURSEMENT_REIMBURSEMENT_FK`
    FOREIGN KEY (`reimbursement`)
    REFERENCES `Reimbursement` (`reimbursement_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Address` ;

CREATE TABLE IF NOT EXISTS `Employee Address` (
  `employee_address_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `address` INT(4) NOT NULL,
  INDEX `EMPLOYEEADRESS_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEADRESS_ADDRESS_idx` (`address` ASC) VISIBLE,
  PRIMARY KEY (`employee_address_id`),
  CONSTRAINT `EMPLOYEEADRESS_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEADRESS_ADDRESS`
    FOREIGN KEY (`address`)
    REFERENCES `Address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment To Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment To Employee` ;

CREATE TABLE IF NOT EXISTS `Payment To Employee` (
  `employee_payment_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NULL,
  `payment` INT(8) NOT NULL,
  INDEX `EMPLOYEEPAYMENT_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEPAYMENT_PAYMENT_FK_idx` (`payment` ASC) VISIBLE,
  PRIMARY KEY (`employee_payment_id`),
  CONSTRAINT `EMPLOYEEPAYMENT_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEPAYMENT_PAYMENT_FK`
    FOREIGN KEY (`payment`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Business Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business Payment` ;

CREATE TABLE IF NOT EXISTS `Business Payment` (
  `business_payment_id` INT(6) NOT NULL AUTO_INCREMENT,
  `business` TINYINT(1) NOT NULL,
  `payment` INT(8) NOT NULL,
  INDEX `BUSINESSPAYMENT_BUSINESS_FK_idx` (`business` ASC) VISIBLE,
  INDEX `BUSINESSPAYMENT_PAYMENT_FK_idx` (`payment` ASC) VISIBLE,
  PRIMARY KEY (`business_payment_id`),
  CONSTRAINT `BUSINESSPAYMENT_BUSINESS_FK`
    FOREIGN KEY (`business`)
    REFERENCES `Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BUSINESSPAYMENT_PAYMENT_FK`
    FOREIGN KEY (`payment`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Reimbursement To Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Reimbursement To Employee` ;

CREATE TABLE IF NOT EXISTS `Reimbursement To Employee` (
  `employee_reimbursement_id` INT(6) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NULL,
  `reimbursement` INT(8) NOT NULL,
  INDEX `EMPLOYEEREIMBURSEMENT_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEREIMBURSEMENT_REIMBURSEMENT_FK_idx` (`reimbursement` ASC) VISIBLE,
  PRIMARY KEY (`employee_reimbursement_id`),
  CONSTRAINT `EMPLOYEEREIMBURSEMENT_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEREIMBURSEMENT_REIMBURSEMENT_FK`
    FOREIGN KEY (`reimbursement`)
    REFERENCES `Reimbursement` (`reimbursement_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Position` ;

CREATE TABLE IF NOT EXISTS `Employee Position` (
  `employee_position_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `position` INT(4) NOT NULL,
  INDEX `EMPLOYEEPOSITON_EMPLOYEE_fk_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEPOSITION_POSITION_FK_idx` (`position` ASC) VISIBLE,
  PRIMARY KEY (`employee_position_id`),
  CONSTRAINT `EMPLOYEEPOSITON_EMPLOYEE_fk`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEPOSITION_POSITION_FK`
    FOREIGN KEY (`position`)
    REFERENCES `Position` (`position_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Wage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Wage` ;

CREATE TABLE IF NOT EXISTS `Employee Wage` (
  `employee_wage_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `wage` INT(6) NOT NULL,
  INDEX `EMPLOYEEWAGE_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEWAGE_WAGE_FK_idx` (`wage` ASC) VISIBLE,
  PRIMARY KEY (`employee_wage_id`),
  CONSTRAINT `EMPLOYEEWAGE_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEWAGE_WAGE_FK`
    FOREIGN KEY (`wage`)
    REFERENCES `Wage` (`wage_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Schedule` ;

CREATE TABLE IF NOT EXISTS `Employee Schedule` (
  `employee_schedule_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `schedule` INT(4) NOT NULL,
  INDEX `EMPLOYEESCHEDULE_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEESCHEDULE_SCHEDULE_FK_idx` (`schedule` ASC) VISIBLE,
  PRIMARY KEY (`employee_schedule_id`),
  CONSTRAINT `EMPLOYEESCHEDULE_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEESCHEDULE_SCHEDULE_FK`
    FOREIGN KEY (`schedule`)
    REFERENCES `Schedule` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Salary` ;

CREATE TABLE IF NOT EXISTS `Employee Salary` (
  `employee_salary_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NULL,
  `salary` INT(6) NOT NULL,
  INDEX `EMPLOYEESALARIES_EMPLOYEE_ID_idx` (`employee` ASC) VISIBLE,
  PRIMARY KEY (`employee_salary_id`),
  INDEX `EMPLOYEESALARY_SALARY_FK_idx` (`salary` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEESALARY_EMPLOYEE_ID`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEESALARY_SALARY_FK`
    FOREIGN KEY (`salary`)
    REFERENCES `Salary` (`salary_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Supplemental Wage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Supplemental Wage` ;

CREATE TABLE IF NOT EXISTS `Employee Supplemental Wage` (
  `employee_supplemental_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NULL,
  `supplemental_wage` INT(8) NOT NULL,
  INDEX `EMPLOYEESUPPLEMENTAL_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  PRIMARY KEY (`employee_supplemental_id`),
  INDEX `EMPLOYEESUPPLEMENT_SUPPLEMENT_FK_idx` (`supplemental_wage` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEESUPPLEMENTAL_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEESUPPLEMENT_SUPPLEMENT_FK`
    FOREIGN KEY (`supplemental_wage`)
    REFERENCES `Supplemental Wage` (`supplemental_wage_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Business Supplemental Wage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business Supplemental Wage` ;

CREATE TABLE IF NOT EXISTS `Business Supplemental Wage` (
  `business_supplemental_id` INT(8) NOT NULL AUTO_INCREMENT,
  `business` TINYINT(1) NOT NULL,
  `supplemental_wage` INT(8) NOT NULL,
  INDEX `BUSINESSSUPPLEMENTAL_BUSINESS_FK_idx` (`business` ASC) VISIBLE,
  PRIMARY KEY (`business_supplemental_id`),
  INDEX `BUSINESSSUPPLEMENTAL_SUPPLEMENTAL_FK_idx` (`supplemental_wage` ASC) VISIBLE,
  CONSTRAINT `BUSINESSSUPPLEMENTAL_BUSINESS_FK`
    FOREIGN KEY (`business`)
    REFERENCES `Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BUSINESSSUPPLEMENTAL_SUPPLEMENTAL_FK`
    FOREIGN KEY (`supplemental_wage`)
    REFERENCES `Supplemental Wage` (`supplemental_wage_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Income Tax Bracket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Income Tax Bracket` ;

CREATE TABLE IF NOT EXISTS `Income Tax Bracket` (
  `income_bracket_id` TINYINT(3) NOT NULL AUTO_INCREMENT,
  `tax_bracket` TINYINT(3) NOT NULL,
  `income_tax` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`income_bracket_id`),
  INDEX `INCOMETAX_BRACKET_FK_idx` (`tax_bracket` ASC) VISIBLE,
  INDEX `INCOMETAX_TAX_FK_idx` (`income_tax` ASC) VISIBLE,
  CONSTRAINT `INCOMETAX_BRACKET_FK`
    FOREIGN KEY (`tax_bracket`)
    REFERENCES `Tax Bracket` (`bracket_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `INCOMETAX_TAX_FK`
    FOREIGN KEY (`income_tax`)
    REFERENCES `Income Tax` (`tax_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Benefit` ;

CREATE TABLE IF NOT EXISTS `Benefit` (
  `benefit_id` INT(3) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `insurance_type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`benefit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Benefit` ;

CREATE TABLE IF NOT EXISTS `Employee Benefit` (
  `employee_benefit_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `benefit` INT(3) NOT NULL,
  INDEX `EMPLOYEEBENEFIT_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEBENEFIT_BENEFIT_FK_idx` (`benefit` ASC) VISIBLE,
  PRIMARY KEY (`employee_benefit_id`),
  CONSTRAINT `EMPLOYEEBENEFIT_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEBENEFIT_BENEFIT_FK`
    FOREIGN KEY (`benefit`)
    REFERENCES `Benefit` (`benefit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Direct Deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Direct Deposit` ;

CREATE TABLE IF NOT EXISTS `Direct Deposit` (
  `deposit_id` INT(6) NOT NULL AUTO_INCREMENT,
  `payment_id` INT(8) NOT NULL,
  `bank_account_number` VARCHAR(13) NOT NULL,
  `routing_number` VARCHAR(9) NOT NULL,
  `bank_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deposit_id`),
  INDEX `DIRECTDEPOSIT_PAYMENT_FK_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `DIRECTDEPOSIT_PAYMENT_FK`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check` ;

CREATE TABLE IF NOT EXISTS `Check` (
  `check_id` INT(6) NOT NULL AUTO_INCREMENT,
  `payment_id` INT(8) NOT NULL,
  `memo` VARCHAR(45) NOT NULL,
  `routing_number` VARCHAR(9) NOT NULL,
  `check_number` CHAR(4) NOT NULL,
  PRIMARY KEY (`check_id`),
  INDEX `CHECK_PAYMENT_FK_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `CHECK_PAYMENT_FK`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Managed By`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Managed By` ;

CREATE TABLE IF NOT EXISTS `Employee Managed By` (
  `employee_manage_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `manager` INT(2) NULL,
  INDEX `EMPLOYEEMANAGED_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEMANAGED_MANAGER_FK_idx` (`manager` ASC) VISIBLE,
  PRIMARY KEY (`employee_manage_id`),
  CONSTRAINT `EMPLOYEEMANAGED_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEMANAGED_MANAGER_FK`
    FOREIGN KEY (`manager`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Bank Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Bank Account` ;

CREATE TABLE IF NOT EXISTS `Employee Bank Account` (
  `employee_bank_id` INT(4) NOT NULL AUTO_INCREMENT,
  `employee` INT(4) NOT NULL,
  `bank_account` INT(4) NOT NULL,
  PRIMARY KEY (`employee_bank_id`),
  INDEX `EMPLOYEEBANK_EMPLOYEE_FK_idx` (`employee` ASC) VISIBLE,
  INDEX `EMPLOYEEBANK_BANK_FK_idx` (`bank_account` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEEBANK_EMPLOYEE_FK`
    FOREIGN KEY (`employee`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEEBANK_BANK_FK`
    FOREIGN KEY (`bank_account`)
    REFERENCES `Bank Account` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Business Bank Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Business Bank Account` ;

CREATE TABLE IF NOT EXISTS `Business Bank Account` (
  `business_bank_id` INT(4) NOT NULL AUTO_INCREMENT,
  `business` TINYINT(2) NOT NULL,
  `bank_account` INT(4) NOT NULL,
  PRIMARY KEY (`business_bank_id`),
  INDEX `BUSINESSBANK_BUSINESS_FK_idx` (`business` ASC) VISIBLE,
  INDEX `BUSINESSBANK_BANK_FK_idx` (`bank_account` ASC) VISIBLE,
  CONSTRAINT `BUSINESSBANK_BUSINESS_FK`
    FOREIGN KEY (`business`)
    REFERENCES `Business` (`business_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BUSINESSBANK_BANK_FK`
    FOREIGN KEY (`bank_account`)
    REFERENCES `Bank Account` (`bank_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
